### ISSUE TITLE
when the connection is lost the script cannot establish a connection

### ISSUE THREAD

**Issue by sbarkhudaryan** [olkal/RPI-MQTT-shutdown#1]
May 31 12:23:26 raspberrypi mqtt_shutdown[338]: Traceback (most recent call last):
May 31 12:23:26 raspberrypi mqtt_shutdown[338]:   File "/usr/local/bin/RPI-MQTT-shutdown/mqtt_shutdown.py", line 43, in <module>
May 31 12:23:26 raspberrypi mqtt_shutdown[338]:     MyClient.connect(brokerAdr, brokerPort) # Connect to the test MQTT broker
May 31 12:23:26 raspberrypi mqtt_shutdown[338]:   File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 914, in connect
May 31 12:23:26 raspberrypi mqtt_shutdown[338]:     return self.reconnect()
May 31 12:23:26 raspberrypi mqtt_shutdown[338]:   File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1044, in reconnect
May 31 12:23:26 raspberrypi mqtt_shutdown[338]:     sock = self._create_socket_connection()
May 31 12:23:26 raspberrypi mqtt_shutdown[338]:   File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
May 31 12:23:26 raspberrypi mqtt_shutdown[338]:     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
May 31 12:23:26 raspberrypi mqtt_shutdown[338]:   File "/usr/lib/python2.7/socket.py", line 557, in create_connection
May 31 12:23:26 raspberrypi mqtt_shutdown[338]:     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
May 31 12:23:26 raspberrypi mqtt_shutdown[338]: socket.gaierror: [Errno -3] Temporary failure in name resolution
May 31 12:23:26 raspberrypi systemd[1]: mqtt_shutdown.service: Main process exited, code=exited, status=1/FAILURE

**Comment by olkal** [comment]
Moved `subscribe` to `connectFunction` and some other minor changes, should be okay now.
